apiVersion: v1
kind: Service
metadata:
  name: hackathon-starter-frontend
spec:
  selector:
    app: hackathon-starter-frontend
  ports:
    - protocol: TCP
      port: 3000 # Port service
      targetPort: 3000 # Port container